"""Add event calendar table

Revision ID: 49d823fbda9a
Revises: 69898c63eae1
Create Date: 2020-09-07 03:20:22.978456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d823fbda9a'
down_revision = '69898c63eae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('first_date', sa.Date(), nullable=False),
    sa.Column('repeat_configuration', sa.Enum('ONCE', 'WEEKLY', 'FORTNIGHTLY', 'MONTHLY', name='repeatconfiguration'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['api_keys.creator'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    op.drop_table('events')
    # ### end Alembic commands ###
