"""Add creator column to events

Revision ID: 4ca713e8ab2d
Revises: 49d823fbda9a
Create Date: 2020-09-07 04:04:34.234229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca713e8ab2d'
down_revision = '49d823fbda9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('creator', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'creator')
    # ### end Alembic commands ###
