"""creator should be unique on APIKey

Revision ID: 69898c63eae1
Revises: 7c1e00c61cc7
Create Date: 2020-08-10 00:40:44.245951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69898c63eae1'
down_revision = '7c1e00c61cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'api_keys', ['creator'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_keys', type_='unique')
    # ### end Alembic commands ###
