"""Add duration_days column to events

Revision ID: eec54fc7b1c6
Revises: 4ca713e8ab2d
Create Date: 2020-09-07 21:42:54.248005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec54fc7b1c6'
down_revision = '4ca713e8ab2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('duration_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'duration_days')
    # ### end Alembic commands ###
