"""Remove duration_days, it isn't used.

Revision ID: ff8ccec457e9
Revises: eec54fc7b1c6
Create Date: 2020-11-01 20:24:47.805623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8ccec457e9'
down_revision = 'eec54fc7b1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'duration_days')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
