"""Add clicks column.

Revision ID: 370d53e800de
Revises: 31a9c659a337
Create Date: 2020-07-30 22:17:01.669889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370d53e800de'
down_revision = '31a9c659a337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortURL', sa.Column('clicks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortURL', 'clicks')
    # ### end Alembic commands ###
