"""Change creator to bigint instead of integer

Revision ID: 4080d3e0041b
Revises: f2bd3a3546c6
Create Date: 2020-07-30 22:31:21.479425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4080d3e0041b'
down_revision = 'f2bd3a3546c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortURL', sa.Column('creator', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortURL', 'creator')
    # ### end Alembic commands ###
