"""empty message

Revision ID: 6ae7c75cefbd
Revises: d40325d49253
Create Date: 2020-08-09 03:03:13.470294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae7c75cefbd'
down_revision = 'd40325d49253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortURL', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortURL', 'notes')
    # ### end Alembic commands ###
