"""Add creator to API keys for forced creator set

Revision ID: d40325d49253
Revises: 3e5e56efb888
Create Date: 2020-07-31 12:42:48.780569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40325d49253'
down_revision = '3e5e56efb888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('creator', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'creator')
    # ### end Alembic commands ###
