"""Change creator to bigint instead of integer

Revision ID: f2bd3a3546c6
Revises: a16cc4688a6e
Create Date: 2020-07-30 22:31:07.666103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2bd3a3546c6'
down_revision = 'a16cc4688a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortURL', 'creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortURL', sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
